apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jio-auth
  namespace: cicd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jiwon-tech-innovation/jio-gitops.git
    targetRevision: HEAD
    path: apps/jio-auth/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: jiaa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
